### ISSUE TITLE
SvcBspDecal has conflicting information

### ISSUE THREAD

**Issue by superselect** [NeKzor/dem#2]
A few fields of SvcBspDecal (DecalTextureIndex and LowPriority) have differing values between the size fields.
I'm not writing a demo parser for portal, so I cannot confirm which value is correct for DecalTextureIndex, but for tf2 its 9 bits, not 1.125 bytes.

PS: Thanks for making this, it has been a very useful resource.

**Comment by pektezol** [comment]
doesn't 1.125 bytes make 9 bits? that part is correct, but size in bytes of EntityIndex, ModelIndex and size in bits of LowPriority is wrong, making a pr
